export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const countries: Country[] = [
  { name: "Sénégal", code: "+221", flag: "🇸🇳" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Côte d'Ivoire", code: "+225", flag: "🇨🇮" },
  { name: "Mali", code: "+223", flag: "🇲🇱" },
  { name: "Guinée", code: "+224", flag: "🇬🇳" },
  { name: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { name: "Bénin", code: "+229", flag: "🇧🇯" },
  { name: "Togo", code: "+228", flag: "🇹🇬" },
  { name: "Cameroun", code: "+237", flag: "🇨🇲" },
  { name: "Gabon", code: "+241", flag: "🇬🇦" },
  { name: "Congo (Brazzaville)", code: "+242", flag: "🇨🇬" },
  { name: "Congo (RDC)", code: "+243", flag: "🇨🇩" },
  { name: "Maroc", code: "+212", flag: "🇲🇦" },
  { name: "Algérie", code: "+213", flag: "🇩🇿" },
  { name: "Tunisie", code: "+216", flag: "🇹🇳" },
  { name: "États-Unis", code: "+1", flag: "🇺🇸" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Belgique", code: "+32", flag: "🇧🇪" },
  { name: "Suisse", code: "+41", flag: "🇨🇭" },
  { name: "Espagne", code: "+34", flag: "🇪🇸" },
  { name: "Italie", code: "+39", flag: "🇮🇹" },
  { name: "Allemagne", code: "+49", flag: "🇩🇪" },
  { name: "Royaume-Uni", code: "+44", flag: "🇬🇧" },
  { name: "Portugal", code: "+351", flag: "🇵🇹" },
  { name: "Luxembourg", code: "+352", flag: "🇱🇺" },
  { name: "Mauritanie", code: "+222", flag: "🇲🇷" },
  { name: "Gambie", code: "+220", flag: "🇬🇲" },
  { name: "Guinée-Bissau", code: "+245", flag: "🇬🇼" },
  { name: "Cap-Vert", code: "+238", flag: "🇨🇻" },
  { name: "Niger", code: "+227", flag: "🇳🇪" },
  { name: "Tchad", code: "+235", flag: "🇹🇩" },
  { name: "République Centrafricaine", code: "+236", flag: "🇨🇫" },
  { name: "Guinée Équatoriale", code: "+240", flag: "🇬🇶" },
  { name: "Djibouti", code: "+253", flag: "🇩🇯" },
  { name: "Comores", code: "+269", flag: "🇰🇲" },
  { name: "Madagascar", code: "+261", flag: "🇲🇬" },
  { name: "Maurice", code: "+230", flag: "🇲🇺" },
  { name: "Seychelles", code: "+248", flag: "🇸🇨" },
  { name: "Haïti", code: "+509", flag: "🇭🇹" },
  { name: "Liban", code: "+961", flag: "🇱🇧" },
  { name: "Égypte", code: "+20", flag: "🇪🇬" },
  { name: "Afrique du Sud", code: "+27", flag: "🇿🇦" },
  { name: "Nigéria", code: "+234", flag: "🇳🇬" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "Éthiopie", code: "+251", flag: "🇪🇹" },
  { name: "Brésil", code: "+55", flag: "🇧🇷" },
  { name: "Chine", code: "+86", flag: "🇨🇳" },
  { name: "Inde", code: "+91", flag: "🇮🇳" },
  { name: "Japon", code: "+81", flag: "🇯🇵" },
  { name: "Corée du Sud", code: "+82", flag: "🇰🇷" },
  { name: "Australie", code: "+61", flag: "🇦🇺" },
  { name: "Émirats Arabes Unis", code: "+971", flag: "🇦🇪" },
  { name: "Arabie Saoudite", code: "+966", flag: "🇸🇦" },
  { name: "Qatar", code: "+974", flag: "🇶🇦" },
  { name: "Turquie", code: "+90", flag: "🇹🇷" },
  { name: "Russie", code: "+7", flag: "🇷🇺" },
].sort((a, b) => a.name.localeCompare(b.name));